name: Vitest Tests on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Merge PR into develop
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout main
        git merge ${{ github.event.pull_request.head.sha }}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Determine package manager and install dependencies
      run: |
        if [ -f "yarn.lock" ]; then
          echo "Using Yarn"
          yarn install --frozen-lockfile
        elif [ -f "package-lock.json" ]; then
          echo "Using npm ci"
          npm ci
        else
          echo "No lockfile found, using npm install"
          npm install
        fi

    - name: Run Vitest tests
      run: |
        if [ -f "yarn.lock" ]; then
          yarn test
        else
          npm run test
        fi

    - name: Generate coverage report
      run: |
        if [ -f "yarn.lock" ]; then
          yarn coverage
        else
          npm run coverage
        fi

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
