name: UI Tests

on:
  pull_request:
    branches: [ main, Development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Merge PR into main
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout main
        git merge ${{ github.event.pull_request.head.sha }}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Determine package manager
      id: check-pm
      run: |
        if [ -f "yarn.lock" ]; then
          echo "manager=yarn" >> $GITHUB_OUTPUT
          echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
        else
          echo "manager=npm" >> $GITHUB_OUTPUT
          echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
        fi

    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.npm
          ~/.cache/yarn
          node_modules
        key: ${{ runner.os }}-${{ steps.check-pm.outputs.manager }}-${{ hashFiles(format('**/{0}', steps.check-pm.outputs.lockfile)) }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.check-pm.outputs.manager }}-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        if [ "${{ steps.check-pm.outputs.manager }}" = "yarn" ]; then
          yarn install --frozen-lockfile
        else
          npm ci
        fi

    - name: Run Vitest tests
      run: |
        if [ "${{ steps.check-pm.outputs.manager }}" = "yarn" ]; then
          yarn test
        else
          npm run test
        fi
